# Generated by Django 2.2.2 on 2020-03-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=140)),
                ('phone_number', models.CharField(max_length=20)),
                ('birth_certificate', models.FileField(upload_to='attachments/certs/')),
                ('id_no', models.FileField(upload_to='attachments/ids/')),
                ('school_name', models.CharField(max_length=128)),
                ('school_address', models.CharField(max_length=140)),
                ('academic_level', models.CharField(choices=[('primary', 'primary'), ('high school', 'high school'), ('diploma', 'diploma'), ('undergraduate', 'undergraduate'), ('masters', 'masters'), ('PhD', 'PhD')], default='primary', max_length=32)),
                ('recommendation_reason', models.TextField(max_length=256)),
                ('recommendation_letter', models.FileField(upload_to='attachments/letters/')),
                ('application_status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=32)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('application_status', '-date_applied'),
            },
        ),
    ]
