# Generated by Django 2.2.2 on 2020-03-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_scholarshipapplication_auth_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='email',
            field=models.EmailField(default='default@mail.com', max_length=254),
            preserve_default=False,
        ),
    ]
